/// Use unwinding for error propagation.
///
/// This attribute can be applied to functions and function declarations in traits. For closures,
/// see [`closure!`].
///
///
/// # Attributes
///
/// Rust evaluates attribute macros from top to bottom, so if `#[iex]` is not the only attribute
/// macro applied to the function/closure, the macros listed above it will be applied to the
/// original definition, and the macros listed below it will be applied to an internal closure
/// generated by `#[iex]`.
///
/// Note that this only applies to attribute *macros*; normal attributes, such as `#[inline]` and
/// `#[cfg]`, do the right thing independently from their location.
///
///
/// # Documentation
///
/// `#[iex]` functions are documented (by rustdoc) to return an algebraic [`Result`], just like in
/// source code, but they also have an `#[iex]` macro attached to their signature. This is a
/// sufficient indicator for those who know what `#[iex]` is, but if you use `#[iex]` in the public
/// API of a library, you probably want to write that down in prose.
///
/// For a rendered example, see [`example`](crate::example).
///
///
/// # Macros in function body
///
/// `#[iex]` rewrites the AST of the function body. It needs to be able to replace the `?` operator,
/// `return` statements, and all implicitly returned values throughout the function body. Notably,
/// this fails if `?` or `return` are generated by a macro:
///
/// FIXME
///
/// ```compile_fail
/// use iex::iex;
///
/// #[iex]
/// fn returns_result(x: i32) -> Result<i32, i32> { Ok(x) }
///
/// macro_rules! ok {
///     ($e:expr) => {
///         // the `?` operator cannot be applied to type `..`
///         returns_result($e)?
///     };
/// }
///
/// #[iex]
/// fn test() -> Result<i32, i32> {
///     Err(ok!(123))
/// }
/// ```
///
///
/// # Example
///
/// ```
/// use iex::iex;
///
/// fn returning_regular_result<E>(err: E) -> Result<(), E> { Err(err) }
///
/// #[iex]
/// fn returning_iex_result<E>(err: E) -> Result<(), E> { Err(err) }
///
/// #[iex]
/// fn test() -> Result<i32, String> {
///     // `?` can be applied to a `Result<_, String>`
///     returning_regular_result("Some error happened!".to_string())?;
///
///     // `?` can be applied to a `Result<_, impl Into<String>>` too
///     returning_regular_result("Some error happened!")?;
///
///     // The same applies to `#[iex] Result`
///     returning_iex_result("Some error happened!".to_string())?;
///     returning_iex_result("Some error happened!")?;
///
///     // You can also directly return a `Result` or an `#[iex] Result`
///     Ok(123)
/// }
///
/// fn main() {
///     // Using an `#[iex]` function from a regular function requires a cast
///     let _result: Result<i32, String> = test().into_result();
/// }
/// ```
///
/// This attribute can only be applied to functions that return a [`Result`]:
///
/// ```compile_fail
/// use iex::iex;
///
/// // the trait `Outcome` is not implemented for `Option<()>`
/// #[iex]
/// fn invalid_example() -> Option<()> {
///     None
/// }
/// ```
///
/// ```compile_fail
/// use iex::iex;
///
/// // the trait `Outcome` is not implemented for `()`
/// #[iex]
/// fn invalid_example() {}
/// ```
pub use iex_derive::iex;

/// Use unwinding for error propagation.
///
/// This attribute can only be applied to closures. See [`#[iex]`](macro@iex) for more info.
///
///
/// # Example
///
/// ```
/// let closure = iex::closure!(|| Ok::<i32, String>(1));
/// assert_eq!(closure().into_result(), Ok(1));
/// ```
///
/// This attribute can only be applied to closures that return a [`Result`]:
///
/// FIXME
pub use iex_derive::closure;
